[package]
name = "scel2rime"
version = "0.1.0"
authors = ["godcrying <godcrying1202@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2"
byteorder = "1.3"
clap = "2.33"